# Generated by Django 3.0.5 on 2020-05-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_manager', 'Can see all things'),)},
        ),
    ]
