# Generated by Django 3.0.5 on 2020-05-25 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['-date', '-created']},
        ),
        migrations.AddField(
            model_name='cases',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
