# Generated by Django 3.0.5 on 2020-05-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
