# Generated by Django 3.0.5 on 2020-04-27 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 12, 0, 25, 975082, tzinfo=utc)),
        ),
    ]
