# Generated by Django 3.0.5 on 2020-04-27 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20200427_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 13, 14, 52, 106965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
