# Generated by Django 3.0.5 on 2020-04-27 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20200427_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 13, 15, 22, 538103, tzinfo=utc)),
        ),
    ]
