# Generated by Django 3.0.5 on 2020-04-27 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20200427_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 13, 16, 29, 869139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
