# Generated by Django 3.0.5 on 2020-04-27 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20200427_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
