# Generated by Django 3.0.5 on 2020-04-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200427_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['-date'], 'permissions': (('is_manager', 'Can see all things'),)},
        ),
    ]
