# Generated by Django 3.0.5 on 2020-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200430_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='time',
            field=models.IntegerField(max_length=4),
        ),
    ]
