# Generated by Django 3.0.5 on 2020-05-10 19:55

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20200502_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='time',
            field=models.IntegerField(validators=[report.models.validate_time]),
        ),
    ]
