# Generated by Django 3.0.5 on 2020-05-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20200510_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['-date']},
        ),
    ]
