# Generated by Django 3.0.5 on 2020-05-31 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casecode', models.CharField(max_length=250)),
                ('deadline_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline_time', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('r', 'rec'), ('d', 'done')], default='r', max_length=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline_date', 'deadline_time', '-author'],
            },
        ),
    ]
